# This workflow builds and uploads python artifacts

name: Publish Development Package
on:
  push:
    branches:
      - master

jobs:
  deploy-package:
    permissions:
      contents: write
      id-token: write
      actions: write
    uses: irvingleonard/reusable-workflows/.github/workflows/deploy-package-dev.yml@v0.0.1
    with:
      package-name: ${{ vars.PACKAGE_NAME }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
